language: python
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=coverage
install:
  - if [ x$TOXENV == "xcoverage" ]; then pip install coveralls; fi
  - pip install tox
script:
  - tox
after_success:
  - if [ x$TOX_ENV == "xcoverage" ]; then coveralls; fi
