language: python
python: 2.7
matrix:
  include:
    - python: "pypy"
      env: TOX_ENV=pypy
    - python: "3.4"
      env: TOX_ENV=py34
    - python: "2.7"
      env: TOX_ENV=py27
install:
  - pip install tox
script:
  - tox -e $TOX_ENV