language: python
matrix:
  include:
    - python: "pypy"
      env: TOX_ENV=pypy
    - python: "3.4"
      env: TOX_ENV=py34
    - python: "2.7"
      env: TOX_ENV=py27
install:
  - pip install coveralls
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
